// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfgy7x1oYMMH8QcxCn0zMosFM7fEj2ffk',
    appId: '1:999344200783:android:6f7ce362a700d1cfc29e3a',
    messagingSenderId: '999344200783',
    projectId: 'appecommerce-d6bc7',
    authDomain: 'ecommerceflutter-61f6d.firebaseapp.com',
    storageBucket: 'appecommerce-d6bc7.appspot.com',
    measurementId: 'G-9M3S52GV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgy7x1oYMMH8QcxCn0zMosFM7fEj2ffk',
    appId: '1:999344200783:android:6f7ce362a700d1cfc29e3a',
    messagingSenderId: '999344200783',
    projectId: 'appecommerce-d6bc7',
    databaseURL:
        'https://appecommerce-d6bc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appecommerce-d6bc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgy7x1oYMMH8QcxCn0zMosFM7fEj2ffk',
    appId: '1:999344200783:android:6f7ce362a700d1cfc29e3a',
    messagingSenderId: '999344200783',
    projectId: 'appecommerce-d6bc7',
    databaseURL:
        'https://appecommerce-d6bc7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appecommerce-d6bc7.appspot.com',
    iosBundleId: 'com.example.ecommercettl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgy7x1oYMMH8QcxCn0zMosFM7fEj2ffk',
    appId: '1:81762041969:ios:6d2c53e17261d165845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    iosBundleId: 'com.example.ecommercettl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfgy7x1oYMMH8QcxCn0zMosFM7fEj2ffk',
    appId: '1:81762041969:web:daf384121bbca54a845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    authDomain: 'ecommerceflutter-61f6d.firebaseapp.com',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    measurementId: 'G-1F62D7DNQK',
  );
}
