// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Fol7pLuri2RCurxL8qIvRpZLO8nqkvk',
    appId: '1:81762041969:web:2ca27b744b4c8022845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    authDomain: 'ecommerceflutter-61f6d.firebaseapp.com',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    measurementId: 'G-9M3S52GV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MzREIj-Au8-6qqIpJRtW74buQh74QxU',
    appId: '1:81762041969:android:6bc8c73ae39f7b7d845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnnYfL-wtBwqaDqe_lBTEImy3t5pE5a9c',
    appId: '1:81762041969:ios:6d2c53e17261d165845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    iosBundleId: 'com.example.ecommercettl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnnYfL-wtBwqaDqe_lBTEImy3t5pE5a9c',
    appId: '1:81762041969:ios:6d2c53e17261d165845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    iosBundleId: 'com.example.ecommercettl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Fol7pLuri2RCurxL8qIvRpZLO8nqkvk',
    appId: '1:81762041969:web:daf384121bbca54a845bd0',
    messagingSenderId: '81762041969',
    projectId: 'ecommerceflutter-61f6d',
    authDomain: 'ecommerceflutter-61f6d.firebaseapp.com',
    storageBucket: 'ecommerceflutter-61f6d.appspot.com',
    measurementId: 'G-1F62D7DNQK',
  );

}